### PR TITLE
Fix missing hard diffs

### LINKED ISSUE #12: Highlighting ruins hard diffs
Coining the term "hard" diffs to differentiate background diffs between the harder diffs:
image

### PR DESCRIPTION
**Pull request by REslim30**
resolves #12

### CODE REVIEW

File: content-script.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
 const _allCodeLinesCssSelector = "[data-qa=code-line] pre > span:last-child";
+const _allPrDiffCodeBlocks = "article[data-qa=pr-diff-file-styles]";
```
Comment (REslim30) [inline content-script.js:2]: Think we should think of a better name than this

Comment (REslim30) [reply content-script.js:2]: `diffFile` is tenable.

File: content-script.js [hunk 2]
```diff
@@ -14,32 +15,20 @@ const allDiffsObserver = new MutationObserver((mutations) => {
...
 
-function highlightDiff(codeLine) {
-  // Try to get the extension of the file
-  const article = codeLine.closest('article[data-qa="pr-diff-file-styles"]');
-  const ariaAttribute = article.getAttribute("aria-label");
-
-  const extension = getExtension(ariaAttribute);
-
-  article.querySelectorAll(_allCodeLinesCssSelector).forEach((node) => {
+function highlightDiff(diffFile) {
```
Comment (REslim30) [inline content-script.js:25]: This should be renamed to diffFile or something.
